jwt:
  secret:
    key: UaRCtKyeTQQ0NxHfMihn/2uMw+KpqzRR5+gb9jYrt1c=
    expiration: 31536000
  refresh:
    key: mLgR+2Jk8wYTf3N9bKuD/Hx2VmNxFqTz8WZo+Lg2SyE=
    expiration: 31536000
###
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ulma.e204@gmail.com
    password: whns lfpg kxur huhk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
  # =====================
  # Redis Configuration
  # =====================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ulma

  data:
    redis:
      host: j11e204.p.ssafy.io
      port: 6379
###
sms:
  key: NCSNCZYDSN3O3B2F
  secret-key: UPT00PRJLIXAM7THC9KX1UGOK6IDVUIH

ssafy:
  app:
    key: 87f1e7815daf4f09a9f1c6e6c2b11be8
