jwt:
  secret:
    key: UaRCtKyeTQQ0NxHfMihn/2uMw+KpqzRR5+gb9jYrt1c=
    expiration: 86400
  refresh:
    key: mLgR+2Jk8wYTf3N9bKuD/Hx2VmNxFqTz8WZo+Lg2SyE=
    expiration: 31536000
###
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ulma.e204@gmail.com
    password: whns lfpg kxur huhk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
  # =====================
  # Redis Configuration
  # =====================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testuser
    password: testpassword
    url: jdbc:mysql://j11e204.p.ssafy.io:3306/contest

  data:
    redis:
      host: j11e204.p.ssafy.io
      port: 6379
###
sms:
  key: NCSNCZYDSN3O3B2F
  secret-key: UPT00PRJLIXAM7THC9KX1UGOK6IDVUIH