# =====================
# MySQL DataSource Configuration (Master/Slave)
# =====================
spring:
  datasource:
    # 마스터 데이터베이스 설정 (쓰기/읽기)
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST_MASTER:localhost}:3306/${MYSQL_DATABASE}
      username: ${MYSQL_USER=:root}
      password: ${MYSQL_PASSWORD:1234}

    # 슬레이브 데이터베이스 설정 (읽기 전용)
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST_SLAVE:localhost}:3306/${MYSQL_DATABASE}
      username: ${MYSQL_REPLICATION_USER:root}
      password: ${MYSQL_REPLICATION_PASSWORD=:1234}
