export const banks = [
  // {name: '한국은행', code: '001'},
  // {name: '산업은행', code: '002'},
  {name: '기업은행', code: '003'},
  {name: '국민은행', code: '004'},
  // {name: '외환은행', code: '005'},
  // {name: '수협중앙회', code: '007'},
  // {name: '수출입은행', code: '008'},
  {name: '농협은행', code: '011'},
  // {name: '지역농축협', code: '012'},
  {name: '우리은행', code: '020'},
  {name: 'SC은행', code: '023'},
  // {name: '한국씨티은행', code: '027'},
  // {name: '대구은행', code: '031'},
  {name: '부산은행', code: '032'},
  // {name: '광주은행', code: '034'},
  // {name: '제주은행', code: '035'},
  // {name: '전북은행', code: '037'},
  {name: '경남은행', code: '039'},
  // {name: '새마을금고중앙회', code: '045'},
  // {name: '신협중앙회', code: '048'},
  // {name: '상호저축은행', code: '050'},
  // {name: '중국은행', code: '051'},
  // {name: '모건스탠리은행', code: '052'},
  // {name: 'HSBC은행', code: '054'},
  // {name: '도이치은행', code: '055'},
  // {name: '알비에스피엘씨은행', code: '056'},
  // {name: '제이피모간체이스은행', code: '057'},
  // {name: '미즈호은행', code: '058'},
  // {name: '미쓰비시도쿄UFJ은행', code: '059'},
  // {name: 'BOA은행', code: '060'},
  // {name: '비엔피파리바은행', code: '061'},
  // {name: '중국공상은행', code: '062'},
  // {name: '산림조합중앙회', code: '064'},
  {name: '우체국', code: '071'},
  // {name: '신용보증기금', code: '076'},
  // {name: '기술보증기금', code: '077'},
  {name: 'KEB하나은행', code: '081'},
  {name: '신한은행', code: '088'},
  {name: '케이뱅크', code: '089'},
  {name: '카카오뱅크', code: '090'},
  {name: '토스뱅크', code: '092'},
  {name: '얼마페이', code: '123'},
  // {name: 'TEST', code: '999'},
];
